// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3fU0S4ESqxjkewzM_P5_dtSoINEZHaw',
    appId: '1:152754714752:web:71725c2aea8b6fe94a0e65',
    messagingSenderId: '152754714752',
    projectId: 'notifcation-48490',
    authDomain: 'notifcation-48490.firebaseapp.com',
    storageBucket: 'notifcation-48490.appspot.com',
    measurementId: 'G-10QYT0ZKMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcxPYF4a8VUA1pCaXQrowTODxPkk-Gh0',
    appId: '1:152754714752:android:0bb96a539b602ed94a0e65',
    messagingSenderId: '152754714752',
    projectId: 'notifcation-48490',
    storageBucket: 'notifcation-48490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9wfBzgTqR5ziGmBIbaVmkPol4NvFJtE',
    appId: '1:152754714752:ios:cc05dc18010d2da14a0e65',
    messagingSenderId: '152754714752',
    projectId: 'notifcation-48490',
    storageBucket: 'notifcation-48490.appspot.com',
    iosClientId: '152754714752-98r97b8821kol7ol189ionmltsau33rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM9wfBzgTqR5ziGmBIbaVmkPol4NvFJtE',
    appId: '1:152754714752:ios:cc05dc18010d2da14a0e65',
    messagingSenderId: '152754714752',
    projectId: 'notifcation-48490',
    storageBucket: 'notifcation-48490.appspot.com',
    iosClientId: '152754714752-98r97b8821kol7ol189ionmltsau33rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );
}
